#!/usr/bin/env bash

PROJECT_FOLDER="$(cd "$(dirname "$(realpath "$0")")/../" &>/dev/null && pwd)"

RECIPIENT_EMAIL="${1}"
ZIP_PATH="${PROJECT_FOLDER}/webp-output.zip"

zip -r "${ZIP_PATH}" "${PROJECT_FOLDER}/output/"

curl -v --url 'smtps://smtp.gmail.com:465' \
  --ssl-reqd \
  --mail-from "${EMAIL_USERNAME}" \
  --mail-rcpt "${RECIPIENT_EMAIL}" \
  --mail-rcpt "${EMAIL_USERNAME}" \
  --user "${EMAIL_USERNAME}:${EMAIL_PASSWORD}" \
  -F '=(;type=multipart/mixed' \
  -F "=Hi!

Your images have been converted to WebP format. You will find them in the attached zip file.

This message was auto-generated by img2webp. For any issues contact ${EMAIL_USERNAME}.

See you soon!
;type=text/plain" \
  -F "file=@${ZIP_PATH};type=application/zip;encoder=base64" \
  -F '=)' \
  -H "Subject: Your converted WebP images" \
  -H "From: img2webp <${EMAIL_USERNAME}>" \
  -H "To: ${RECIPIENT_EMAIL} <${RECIPIENT_EMAIL}>"
